version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.28.1
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
