changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/*.spec.{js,ts,tsx}'

npmAuthToken: '${NPM_AUTH_TOKEN-emptytoken}'

packageExtensions:
  remark-parse@*:
    dependencies:
      unist-util-stringify-position: '^2.0.3'
  mdast-util-from-markdown@*:
    peerDependencies:
      unist-util-stringify-position: '*'
  gatsby@*:
    peerDependencies:
      babel-plugin-styled-components: '*'
  styled-components@*:
    dependencies:
      react-is: '^16'
  d3-array@*:
    peerDependencies:
      regenerator-runtime: '*'
  vega-dataflow@*:
    peerDependencies:
      regenerator-runtime: '*'
  vega-loader@*:
    peerDependencies:
      regenerator-runtime: '*'
  vega-statistics@*:
    peerDependencies:
      regenerator-runtime: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-2.3.0.cjs
