version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: 'Dockerfile'
    volumes:
      - .:/ws:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - 'NODE_CONFIG_ENV=codespaces'
